export const DEFAULT_POLLING_INTERVAL_SECONDS = 15;
export const MIN_POLLING_INTERVAL_SECONDS = 5;
export const MAX_POLLING_INTERVAL_SECONDS = 300;
export const DEFAULT_SNAPSHOT_RETENTION_ENABLED = true;
export const DEFAULT_SNAPSHOT_RETENTION_INTERVAL_SECONDS = 900;
export const MIN_SNAPSHOT_RETENTION_INTERVAL_SECONDS = 60;
export const MAX_SNAPSHOT_RETENTION_INTERVAL_SECONDS = 86_400;
export const DEFAULT_SNAPSHOT_RETENTION_KEEP_LATEST = 100;
export const MAX_SNAPSHOT_RETENTION_KEEP_LATEST = 1000;
export const DEFAULT_ALERT_ERROR_RATE_THRESHOLD = 0.2;
export const DEFAULT_ALERT_MIN_EVENT_VOLUME = 20;
export const MAX_ALERT_MIN_EVENT_VOLUME = 10_000;
export const DEFAULT_ALERT_DISPATCH_ENABLED = true;
export const DEFAULT_ALERT_DISPATCH_COOLDOWN_SECONDS = 300;
export const MAX_ALERT_DISPATCH_COOLDOWN_SECONDS = 86_400;
export const DEFAULT_ALERT_WEBHOOK_MAX_ATTEMPTS = 3;
export const DEFAULT_ALERT_WEBHOOK_INITIAL_BACKOFF_MS = 250;
export const MAX_ALERT_WEBHOOK_MAX_ATTEMPTS = 10;
export const MAX_ALERT_WEBHOOK_INITIAL_BACKOFF_MS = 60_000;
export const DEFAULT_ALERT_WEBHOOK_MIN_SEVERITY = 'info';
export const DEFAULT_ALERT_WEBHOOK_TEMPLATE = '[{severity}] {code}: {message} | metadata={metadata}';
export const DEFAULT_ALERT_SLACK_ENABLED = false;
export const DEFAULT_ALERT_SLACK_MAX_ATTEMPTS = 3;
export const DEFAULT_ALERT_SLACK_INITIAL_BACKOFF_MS = 250;
export const MAX_ALERT_SLACK_MAX_ATTEMPTS = 10;
export const MAX_ALERT_SLACK_INITIAL_BACKOFF_MS = 60_000;
export const DEFAULT_ALERT_SLACK_MIN_SEVERITY = 'warning';
export const DEFAULT_ALERT_SLACK_TEMPLATE = ':rotating_light: [{severity}] {code} - {message}';
export const DEFAULT_ALERT_EMAIL_ENABLED = false;
export const DEFAULT_ALERT_EMAIL_MAX_ATTEMPTS = 3;
export const DEFAULT_ALERT_EMAIL_INITIAL_BACKOFF_MS = 250;
export const MAX_ALERT_EMAIL_MAX_ATTEMPTS = 10;
export const MAX_ALERT_EMAIL_INITIAL_BACKOFF_MS = 60_000;
export const DEFAULT_ALERT_EMAIL_MIN_SEVERITY = 'critical';
export const DEFAULT_ALERT_EMAIL_TEMPLATE = '[{severity}] {code}\n\n{message}\n\nmetadata={metadata}';
export const DEFAULT_ALERT_ESCALATION_FAILURE_THRESHOLD = 3;
export const MAX_ALERT_ESCALATION_FAILURE_THRESHOLD = 20;
export const DEFAULT_ALERT_MAX_SILENCE_SECONDS = 86_400;
export const MAX_ALERT_MAX_SILENCE_SECONDS = 604_800;
export const DEFAULT_ALERT_IDEMPOTENCY_ENABLED = true;
export const DEFAULT_ALERT_IDEMPOTENCY_TTL_SECONDS = 900;
export const MAX_ALERT_IDEMPOTENCY_TTL_SECONDS = 86_400;
export const DEFAULT_ALERT_RATE_LIMIT_ENABLED = true;
export const DEFAULT_ALERT_RATE_LIMIT_WINDOW_SECONDS = 60;
export const DEFAULT_ALERT_RATE_LIMIT_MAX_REQUESTS = 30;
export const MAX_ALERT_RATE_LIMIT_WINDOW_SECONDS = 3_600;
export const MAX_ALERT_RATE_LIMIT_MAX_REQUESTS = 1_000;

export const DEFAULT_HEURISTIC_WEIGHTS = {
  contractYearBump: 0.2,
  targetShareVolatility: 0.15,
  olineUpgrade: 0.1,
  rzRegression: 0.12,
  gameScriptLeverage: 0.08,
};
